# Generated by Django 2.2.17 on 2020-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecard',
            options={'verbose_name': 'Карточку', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='headarticlecard',
            options={'verbose_name': 'Карточку на главной странице', 'verbose_name_plural': 'Карточки на главной странице'},
        ),
        migrations.RenameField(
            model_name='headarticlecard',
            old_name='articleCard',
            new_name='article_card',
        ),
    ]
